print("Welcome to Personal data collector")
name = input("Enter Yout Name")
print("Welcome", name)
age = input("Enter Your age")
print("your age is",age)
height = input("Enter your height")
print("your height is:",height)
favnum = input("ENTER your favourite number")
print("your favourite number is:",favnum)